# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Hello

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: hi
        run: git clone https://github.com/phetsims/assert.git && git clone https://github.com/phetsims/axon.git && git clone https://github.com/phetsims/babel.git && git clone https://github.com/phetsims/brand.git && git clone https://github.com/phetsims/chipper.git && git clone https://github.com/phetsims/dot.git && git clone https://github.com/phetsims/joist.git && git clone https://github.com/phetsims/kite.git && git clone https://github.com/phetsims/natural-selection.git && git clone https://github.com/phetsims/perennial.git perennial-alias && git clone https://github.com/phetsims/phet-core.git && git clone https://github.com/phetsims/phetcommon.git && git clone https://github.com/phetsims/phetmarks.git && git clone https://github.com/phetsims/query-string-machine.git && git clone https://github.com/phetsims/scenery.git && git clone https://github.com/phetsims/scenery-phet.git && git clone https://github.com/phetsims/sherpa.git && git clone https://github.com/phetsims/sun.git && git clone https://github.com/phetsims/tambo.git && git clone https://github.com/phetsims/tandem.git && git clone https://github.com/phetsims/twixt.git && git clone https://github.com/phetsims/utterance-queue.git
      - name: why
        run: ls
      - name: chipper
        run: cd natural-selection/chipper && npm install
      - name: perennial-alias
        run: cd natural-selection/perennial-alias && npm install
      - name: natural-selection
        run: cd natural-selection/natural-selection && npm install
      - name: start
        run: cd natural-selection && grunt dev-server

