# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Hello

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: chipper
        run: cd chipper && np install
      - name: perennial-alias
        run: cd perennial-alias && npm install
      - name: natural-selection
        run: cd natural-selection && npm install
      - name: start
        run: grunt dev-server

